-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    animations = {
        enabled = false,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})
