exec-once = hyprpaper & swaync & waybar & battery-notifier & hyprsunset & clipcatd & wayscriber --daemon & openwhispr &
exec-once = rm -f /tmp/waybar_caffeine_state && hypridle
exec-once = bash -c 'while true; do wayvnc; sleep 3; done'