general {
    lock_cmd = pidof hyprlock || hyprlock          # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session       # lock before suspend.
    ignore_dbus_inhibit = false                    # respect browser & app idle inhibitors.
}

# Lock session after 60s (unless media is playing)
listener {
    timeout = 60
    on-timeout = pidof hyprlock || [ "$(playerctl status 2>/dev/null)" = "Playing" ] || loginctl lock-session
}
