general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display on resume.
    ignore_dbus_inhibit = false                 # respect browser & app idle inhibitors.
}

# Dim screen after 30s (unless media is playing)
listener {
    timeout = 30
    on-timeout = [ "$(playerctl status 2>/dev/null)" = "Playing" ] || { brightnessctl --save; [ $(brightnessctl get) -ge $(brightnessctl max | awk '{print int($1*0.05)}') ] && brightnessctl set 5%; }
    on-resume = [ $(brightnessctl -m | cut -d, -f4 | tr -d %) -lt 5 ] && brightnessctl set 5% || brightnessctl -r
}

# Turn off keyboard backlight after 30s (unless media is playing)
listener { 
    timeout = 30
    on-timeout = [ "$(playerctl status 2>/dev/null)" = "Playing" ] || brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Lock session after 60s (unless media is playing)
listener {
    timeout = 60
    on-timeout = pidof hyprlock || [ "$(playerctl status 2>/dev/null)" = "Playing" ] || loginctl lock-session
}

# Turn off display after 65s (unless media is playing)
listener {
    timeout = 65
    on-timeout = pidof hyprlock || [ "$(playerctl status 2>/dev/null)" = "Playing" ] || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
